#!/usr/bin/env bash
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# If you want to allow non-ascii filenames set this variable to true.
allownonascii=$(git config hooks.allownonascii)

# Redirect output to stderr.
exec 1>&2

# Cross platform projects tend to avoid non-ascii filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if [ "$allownonascii" != "true" ] &&
	# Note that the use of brackets around a tr range is ok here, (it's
	# even required, for portability to Solaris 10's /usr/bin/tr), since
	# the square bracket bytes happen to fall in the designated range.
	test $(git diff --cached --name-only --diff-filter=A -z $against |
	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
then
	echo "Error: Attempt to add a non-ascii file name."
	echo
	echo "This can cause problems if you want to work"
	echo "with people on other platforms."
	echo
	echo "To be portable it is advisable to rename the file ..."
	echo
	echo "If you know what you are doing you can disable this"
	echo "check using:"
	echo
	echo "  git config hooks.allownonascii true"
	echo
	exit 1
fi

# Check installation of checkers

command -v rubocop >/dev/null 2>&1 || {
  echo "Error: rubocop not installed. It is necessary for checking your Ruby style."
  echo
  echo "Please install rubocop by running: "
  echo "gem install rubocop"
  echo "Then, try committing again."
  exit 1
}

command -v jshint >/dev/null 2>&1 || {
  echo "Error: jshint not installed. It is necessary for checking your Javascript style."
  echo
  command -v npm >/dev/null 2>&1 || {
    echo "You do not have npm installed. It is easiest to install jshint through node. To install, please run these commands:"
    echo

    if [ "$(uname)" == "Darwin" ]
    then
      echo "brew install node"
    elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]
    then
      echo For Debian/Ubuntu:
      echo "sudo apt-get install node"
      echo "sudo apt-get install npm"
    elif [ -n "$COMSPEC" -a -x "$COMSPEC" ]
    then
      # windows
      echo "Go to this link:"
      echo http://nodejs.org/download/
    fi
  }

  echo
  echo "Please install jshint by running: "
  echo "sudo npm install -g jshint"

  echo "Then, try committing again."
  exit 1
}

# Run checkers

# rubocop
git diff --cached --name-only --diff-filter=ACM | while read FILE; do
  if [[ "$FILE" =~ ^.+(\.rb)$ ]]; then
    output=$(rubocop "$FILE")
    if [ $? -ne 0 ]; then
      echo "$output"
      echo "Errors found, please fix and try committing again."
      exit 1
    fi
  fi
done || exit $?

# jshint
git diff --cached --name-only --diff-filter=ACM | while read FILE; do
  if [[ "$FILE" =~ ^.+(\.js)$ ]]; then
    output=$(jshint "$FILE")
    if [ $? -ne 0 ]; then
      echo "$output"
      echo "Errors found, please fix and try committing again."
      exit 1
    fi
  fi
done || exit $?

# If there are whitespace errors, print the offending file names and fail.
exec git diff-index --check --cached $against --
